apiVersion: v1
kind: Service
metadata:
  labels:
    app: course-service
  name: course-service
spec:
  por
        image: {{HUB}}/micro-service/course-service:latest
        ports:
        - containerPort: 20880
      - name: course-edge-service
        image: {{HUB}}/micro-service/course-edge-service:latest
        ports:
        - containerPort: 8081

